name: github pages

on:
  push:
    branches:
      # Set a branch to deploy
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          # Fetch Hugo themes (true OR recursive)
          submodules: true
          # Fetch all history for .GitInfo and .Lastmod
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Check install Hugo
        run: hugo version

      - name: Install dependencies
        run: npm ci

      - name: Check for linting errors
        run: npm test

      - name: Delete temporary directories
        run: npm run clean

      - name: Build production website
        run: npm run build

      - name: Build
        run: hugo --gc --minify --cleanDestinationDir

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.HUGO_TOKEN }}
          publish_dir: ./public
